### ISSUE TITLE
Issue in setting up the local enviroment

### ISSUE THREAD

**Issue by divyanshu-rawat** [Grasia/teem#363]
After running `sudo npm install` in the working directory I am receiving this warning.

`npm WARN lifecycle teem@0.0.3~postinstall: cannot run in wd %s %s (wd=%s) teem@0.0.3 bower install /home/divyanshu/Music/teem`

Npm is not running `"postinstall": "bower install"` .
So, Bower components are not installing.
I also tried running `sudo npm run postinstall ` manually even it is not working.

**Comment by suvigyavijay** [comment]
Just manually run bower to fix the issue after running npm install.
`bower install`

[https://github.com/npm/npm/issues/3497](url)
As mentioned the issue is caused by npm trying to downgrade its privileges to run bower.
Even using `--unsafe-perm` with `sudo` will cause an issue as bower doesn't require sudo.

**Comment by divyanshu-rawat** [comment]
I have already tried running `bower install` but permission is denied i.e I don't have access to bower.json.
I
![issue](https://cloud.githubusercontent.com/assets/13464678/23541139/87d38422-000b-11e7-954e-a950426d8ac0.png)

**Comment by suvigyavijay** [comment]
Have you install bower globally, if not then `npm install -g bower`

If this even doesn't work, try
`sudo bower install --allow-root`

Also are you the administrator?

**Comment by divyanshu-rawat** [comment]
Somehow I managed to find the solution [Bower Issues](https://github.com/bower/bower/issues/2262)
Thank you so much for your time.
Are you also contributing to teem?

**Comment by suvigyavijay** [comment]
Yes.

**Comment by divyanshu-rawat** [comment]
@suvigyavijay  can you help me out dealing with this issue 
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by divyanshu-rawat** [comment]
@atfornes can you help me out dealing with this issue
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by atfornes** [comment]
@divyanshu-rawat, it seems like this issue might help you: https://github.com/docker/compose/issues/1214

**Comment by divyanshu-rawat** [comment]
Still facing issue in setting up @atfornes  
![abc](https://cloud.githubusercontent.com/assets/13464678/23547477/50fb8cba-0029-11e7-89ec-262e647627c8.png)

**Comment by atfornes** [comment]
It still looks like a docker installation/configuration issue.

I am afraid I have not faced this issue before, so I cannot help you better than docker community, try to rise an issue there if what you found does not solve your problem.

Sorry I cannot help further :sad:

**Comment by atd** [comment]
@divyanshu-rawat did you restart your computer, as it is said in the README?

**Comment by divyanshu-rawat** [comment]
@atd I didn't restart my computer I am doing it now. Let's see what happens thanks

**Comment by divyanshu-rawat** [comment]
@atd Docker issue solved but swellrt.js is not loading 
![accc](https://cloud.githubusercontent.com/assets/13464678/23548637/78590120-002e-11e7-8462-589e44a2490a.png)

**Comment by atd** [comment]
Please, wait until docker downloads both mongo and swellrt images

**Comment by suvigyavijay** [comment]
I think the processing is not over yet. Docker will pull swellRT library and then it may work.

**Comment by divyanshu-rawat** [comment]
okay donw but Now what is the meaning of following errors that I am getting in console.
![app](https://cloud.githubusercontent.com/assets/13464678/23548812/42130538-002f-11e7-9215-29db693d6ded.png)

**Comment by atfornes** [comment]
could you try to connect to localhost:9898 and check that SwellRT is running?

**Comment by divyanshu-rawat** [comment]
@atfornes  yes SwellRT is running !
Error I am getting in console is `Application Cache Error event: Failed to parse manifest http://localhost:8000/app.manifest`

**Comment by suvigyavijay** [comment]
Yeah, even I am getting the same error.
> Application Cache Error event: Failed to parse manifest http://localhost:8000/app.manifest

**Comment by divyanshu-rawat** [comment]
@suvigyavijay In order to Login is there any default username and password or I have to register.

**Comment by suvigyavijay** [comment]
Register a test user. The information need not be actual, it is in dev phase.
