### ISSUE TITLE
Gulp process stops with javascript files with syntax errors

### ISSUE THREAD

**Issue by atfornes** [Grasia/teem#4]
If a js file is saved with a syntax error, gulp process die with message like the following:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Error in parsing: "services/swellrt.js", Line 13: Unexpected token ;

The desired behavior is that gulp will continue working despite the syntax error, that would be detected though other channels like the browser console error messages.

**Comment by atd** [comment]
See https://github.com/nfroidure/StreamQueue/issues/7

**Comment by sakshamsaxena** [comment]
So Gulp Plumber didn't help? Any insights on that? I'll give it a go either way.

**Comment by krshubham** [comment]
@atfornes @atd  I was taking a look at this issue. I figured out that using error event with each pipe lets us to handle the error event gracefully. I did write error handler with each pipe and now the whole process doesn't stop and the error is logged into the console also browser console shows the respective error.
You can see in the image that the error has been logged but the process is still working and has not been killed.
![image](https://cloud.githubusercontent.com/assets/16729005/26479350/2f5bad34-41f0-11e7-9870-50083626b9ea.png)

**Comment by atfornes** [comment]
this is really great! thanks @krshubham :)

Do you have a pull request to share?

**Comment by krshubham** [comment]
@atfornes close this issue now?
